batch_size: 1024
entropy_coef: 0.1
env_name: brax-ant-v0
episode_length: 1000
epoch_repeat: 8
epsilon: 0.3
gamma: 0.97
hidden_size: 256
num_envs: 2048
optim: !!python/name:torch.optim.adamw.AdamW ''
policy_lr: 0.0001
samples_per_epoch: 5
value_lr: 0.001
